# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RKParallaxEffect' do

pod 'RKParallaxEffect', '~> 1.0.0'

end

target 'RKParallaxEffectTests' do

end

